---
  - name: Install FluentBit
    shell: curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sh

  - name: Create Paersers File
    copy:
      src: parsers.conf
      dest: /etc/fluent-bit/parsers.conf

  - name: Create Config File
    template:
      src: fluent-bit.conf.j2
      dest: /etc/fluent-bit/fluent-bit.conf
      validate: "/opt/fluent-bit/bin/fluent-bit --config=%s -D"

  - name: Create Rsyslog Config
    copy:
      src: 60-fluent-bit.conf
      dest: /etc/rsyslog.d/60-fluent-bit.conf

  - name: Restart Rsyslog
    systemd:
      name: rsyslog
      state: restarted

  - name: Restart FluentBit
    systemd:
      name: fluent-bit
      state: restarted
      enabled: true

